void AudioComponentFindNext() {}
void AudioComponentInstanceNew() {}
void AudioComponentInstanceDispose() {}
void AudioFileOpenURL() {}
void AudioFileGetPropertyInfo() {}
void AudioFileGetProperty() {}
void AudioFileReadBytes() {}
void AudioFileReadPackets() {}
void AudioFileReadPacketData() {}
void AudioFileOpenWithCallbacks() {}
void AudioFileClose() {}
void AudioFileStreamOpen() {}
void AudioQueueNewOutput() {}
void AudioQueueGetParameter() {}
void AudioQueueSetParameter() {}
void AudioQueueAllocateBufferWithPacketDescriptions() {}
void AudioQueueAllocateBuffer() {}
void AudioQueueEnqueueBuffer() {}
void AudioQueueAddPropertyListener() {}
void AudioQueueRemovePropertyListener() {}
void AudioQueueGetPropertySize() {}
void AudioQueueGetProperty() {}
void AudioQueuePrime() {}
void AudioQueueStart() {}
void AudioQueuePause() {}
void AudioQueueStop() {}
void AudioQueueReset() {}
void AudioQueueFlush() {}
void AudioQueueFreeBuffer() {}
void AudioQueueDispose() {}
void AudioServicesGetProperty() {}
void AudioServicesPlaySystemSound() {}
void AudioSessionInitialize() {}
void AudioSessionGetProperty() {}
void AudioSessionGetPropertySize() {}
void AudioSessionSetProperty() {}
void AudioSessionSetActive() {}
void AudioSessionAddPropertyListener() {}
void AudioUnitInitialize() {}
void AudioUnitUninitialize() {}
void AudioUnitSetProperty() {}
void AudioUnitGetProperty() {}
void AudioOutputUnitStart() {}
void AudioOutputUnitStop() {}
