@interface EAGLContext
@end
@implementation EAGLContext
@end
int kEAGLDrawablePropertyColorFormat;
int kEAGLDrawablePropertyRetainedBacking;
int kEAGLColorFormatRGBA8;
int kEAGLColorFormatRGB565;
void glGetError() {}
void glEnable() {}
void glIsEnabled() {}
void glDisable() {}
void glClientActiveTexture() {}
void glEnableClientState() {}
void glDisableClientState() {}
void glGetBooleanv() {}
void glGetFloatv() {}
void glGetIntegerv() {}
void glGetPointerv() {}
void glGetTexEnviv() {}
void glGetTexEnvfv() {}
void glHint() {}
void glFinish() {}
void glFlush() {}
void glGetString() {}
void glAlphaFunc() {}
void glAlphaFuncx() {}
void glBlendFunc() {}
void glBlendEquationOES() {}
void glColorMask() {}
void glClipPlanef() {}
void glClipPlanex() {}
void glCullFace() {}
void glDepthFunc() {}
void glDepthMask() {}
void glDepthRangef() {}
void glDepthRangex() {}
void glFrontFace() {}
void glPolygonOffset() {}
void glPolygonOffsetx() {}
void glSampleCoverage() {}
void glSampleCoveragex() {}
void glShadeModel() {}
void glScissor() {}
void glViewport() {}
void glLineWidth() {}
void glLineWidthx() {}
void glStencilFunc() {}
void glStencilOp() {}
void glStencilMask() {}
void glPointSize() {}
void glPointSizex() {}
void glPointParameterf() {}
void glPointParameterx() {}
void glPointParameterfv() {}
void glPointParameterxv() {}
void glFogf() {}
void glFogx() {}
void glFogfv() {}
void glFogxv() {}
void glLightf() {}
void glLightx() {}
void glLightfv() {}
void glLightxv() {}
void glLightModelf() {}
void glLightModelfv() {}
void glLightModelx() {}
void glLightModelxv() {}
void glMaterialf() {}
void glMaterialx() {}
void glMaterialfv() {}
void glMaterialxv() {}
void glIsBuffer() {}
void glGenBuffers() {}
void glDeleteBuffers() {}
void glBindBuffer() {}
void glBufferData() {}
void glBufferSubData() {}
void glColor4f() {}
void glColor4x() {}
void glColor4ub() {}
void glNormal3f() {}
void glNormal3x() {}
void glColorPointer() {}
void glNormalPointer() {}
void glTexCoordPointer() {}
void glVertexPointer() {}
void glDrawArrays() {}
void glDrawElements() {}
void glClear() {}
void glClearColor() {}
void glClearColorx() {}
void glClearDepthf() {}
void glClearDepthx() {}
void glClearStencil() {}
void glMatrixMode() {}
void glLoadIdentity() {}
void glLoadMatrixf() {}
void glLoadMatrixx() {}
void glMultMatrixf() {}
void glMultMatrixx() {}
void glPushMatrix() {}
void glPopMatrix() {}
void glOrthof() {}
void glOrthox() {}
void glFrustumf() {}
void glFrustumx() {}
void glRotatef() {}
void glRotatex() {}
void glScalef() {}
void glScalex() {}
void glTranslatef() {}
void glTranslatex() {}
void glPixelStorei() {}
void glReadPixels() {}
void glGenTextures() {}
void glDeleteTextures() {}
void glActiveTexture() {}
void glIsTexture() {}
void glBindTexture() {}
void glTexParameteri() {}
void glTexParameterf() {}
void glTexParameterx() {}
void glTexParameteriv() {}
void glTexParameterfv() {}
void glTexParameterxv() {}
void glTexImage2D() {}
void glTexSubImage2D() {}
void glCompressedTexImage2D() {}
void glCopyTexImage2D() {}
void glCopyTexSubImage2D() {}
void glTexEnvf() {}
void glTexEnvx() {}
void glTexEnvi() {}
void glTexEnvfv() {}
void glTexEnvxv() {}
void glTexEnviv() {}
void glGenFramebuffersOES() {}
void glGenRenderbuffersOES() {}
void glIsFramebufferOES() {}
void glIsRenderbufferOES() {}
void glBindFramebufferOES() {}
void glBindRenderbufferOES() {}
void glRenderbufferStorageOES() {}
void glFramebufferRenderbufferOES() {}
void glFramebufferTexture2DOES() {}
void glGetFramebufferAttachmentParameterivOES() {}
void glGetRenderbufferParameterivOES() {}
void glCheckFramebufferStatusOES() {}
void glDeleteFramebuffersOES() {}
void glDeleteRenderbuffersOES() {}
void glGenerateMipmapOES() {}
void glGetBufferParameteriv() {}
void glMapBufferOES() {}
void glUnmapBufferOES() {}
