void alcOpenDevice() {}
void alcCloseDevice() {}
void alcGetError() {}
void alcCreateContext() {}
void alcDestroyContext() {}
void alcProcessContext() {}
void alcSuspendContext() {}
void alcMakeContextCurrent() {}
void alcGetProcAddress() {}
void alGetError() {}
void alDistanceModel() {}
void alListenerf() {}
void alListener3f() {}
void alListenerfv() {}
void alListeneri() {}
void alListener3i() {}
void alListeneriv() {}
void alGetListenerf() {}
void alGetListener3f() {}
void alGetListenerfv() {}
void alGetListeneri() {}
void alGetListener3i() {}
void alGetListeneriv() {}
void alGenSources() {}
void alDeleteSources() {}
void alSourcef() {}
void alSource3f() {}
void alSourcefv() {}
void alSourcei() {}
void alSource3i() {}
void alSourceiv() {}
void alGetSourcef() {}
void alGetSource3f() {}
void alGetSourcefv() {}
void alGetSourcei() {}
void alGetSource3i() {}
void alGetSourceiv() {}
void alSourcePlay() {}
void alSourcePause() {}
void alSourceStop() {}
void alSourceRewind() {}
void alSourceQueueBuffers() {}
void alSourceUnqueueBuffers() {}
void alGenBuffers() {}
void alDeleteBuffers() {}
void alBufferData() {}
void alBufferDataStatic() {}
void alcMacOSXMixerOutputRate() {}
void alcMacOSXGetMixerOutputRate() {}
void alcGetContextsDevice() {}
void alcGetCurrentContext() {}
void alcGetEnumValue() {}
void alcGetIntegerv() {}
void alcGetString() {}
void alcIsExtensionPresent() {}
void alIsBuffer() {}
void alGetBufferf() {}
void alGetBufferi() {}
void alEnable() {}
void alDisable() {}
void alDopplerFactor() {}
void alDopplerVelocity() {}
void alGetBoolean() {}
void alGetBooleanv() {}
void alGetDouble() {}
void alGetDoublev() {}
void alGetFloat() {}
void alGetFloatv() {}
void alGetInteger() {}
void alGetIntegerv() {}
void alGetEnumValue() {}
void alGetProcAddress() {}
void alGetString() {}
void alIsExtensionPresent() {}
void alIsEnabled() {}
void alIsSource() {}
void alSourcePlayv() {}
void alSourcePausev() {}
void alSourceStopv() {}
void alSourceRewindv() {}
void alSpeedOfSound() {}
