set(STUBS_SOURCE_DIR "${SOURCES}/system-stubs")
set(STUBS_BINARY_DIR "${CMAKE_BINARY_DIR}/system-stubs-build")
set(STUBS_INSTALL_DIR "${CMAKE_BINARY_DIR}/system-stubs")

include(ExternalProject)

ExternalProject_Add(
    system_stubs
    SOURCE_DIR ${STUBS_SOURCE_DIR}
    BINARY_DIR ${STUBS_BINARY_DIR}
    INSTALL_DIR ${STUBS_INSTALL_DIR}
    CMAKE_ARGS
        -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
        -DCMAKE_INSTALL_PREFIX=${STUBS_INSTALL_DIR}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
)

install(DIRECTORY ${STUBS_INSTALL_DIR}/usr/lib DESTINATION usr)
install(DIRECTORY ${STUBS_INSTALL_DIR}/System DESTINATION .)
