set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".dylib")
set(CMAKE_PLATFORM_HAS_SHARED_LIBRARY TRUE)
set(CMAKE_SUPPORTS_SHARED_LIBRARIES TRUE)
set(CMAKE_LINK_LIBRARY_SUFFIX "")

set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")

set(CMAKE_EXECUTABLE_SUFFIX "")

set(CMAKE_LINK_DEPENDS_NO_SHARED TRUE)

set(CMAKE_CROSSCOMPILING TRUE)

set(APPLE 1)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

foreach(lang C CXX OBJC OBJCXX)
  set(CMAKE_${lang}_OSX_COMPATIBILITY_VERSION_FLAG "-compatibility_version ")
  set(CMAKE_${lang}_OSX_CURRENT_VERSION_FLAG "-current_version ")

  set(CMAKE_SHARED_LIBRARY_CREATE_${lang}_FLAGS "-dynamiclib")
endforeach()

set(CMAKE_SYSTEM_LOADED 1)
